name: CI

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: node:latest
    steps:
      - uses: actions/checkout@v1
      - name: Install
        run: yarn install
      - name: Lint
        run: yarn eslint "**/*.js"
      - name: Test
        run: yarn test

  deploy:
    runs-on: [ubuntu-latest]
    container:
      image: node:latest
    needs: [test]
    steps:
      - name: Install
        run: yarn install
      - name: Build
        run: yarn build
      - name: Deploy
        run: now public -t ${{ secrets.ZEIT_TOKEN }}
      - name: Alias
        branches:
          - master
        run: now alias
