name: CI

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: node:latest
    steps:
      - uses: actions/checkout@v1
      - name: Lint
        run: yarn eslint "**/*.js"
      - name: Test
        run: CI=true yarn test
      - name: CodeCov
        uses: Atrox/codecov-action@v0.1.2
        env: ${{ secrets.CODECOV_TOKEN }}

  deploy:
    runs-on: [ubuntu-latest]
    container:
      image: node:latest
    needs: [test]
    steps:
      - name: Build
        run: yarn build
      - name: Deploy
        uses: actions/zeit-now@master
