name: CI

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: node:latest
    steps:
      - uses: actions/checkout@v1
      - name: Install
        run: yarn install
      - name: Test
        run: yarn test
  
  lint:
    runs-on: [ubuntu-latest]
    container:
      image: node:latest
    steps:
      - uses: actions/checkout@v1
      - name: Install
        run: yarn install
      - name: Lint
        run: yarn eslint "**/*.js"
        

  deploy:
    runs-on: [ubuntu-latest]
    container:
      image: node:latest
    needs: [test, lint]
    steps:
      - uses: actions/checkout@v1
      - name: Install
        run: yarn install
      - name: Build
        run: yarn build
      - name: Deploy
        env:
          ZEIT_TOKEN: ${{ secrets.ZEIT_TOKEN }}
        run: yarn now -t $ZEIT_TOKEN
